In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'1.3.0'

In [3]:
hello = tf.constant("Hello ")

In [4]:
world = tf.constant("World")

In [6]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [7]:
hello

<tf.Tensor 'Const:0' shape=() dtype=string>

In [9]:
with tf.Session() as sess:
    res=sess.run(hello+world)

In [10]:
res

b'Hello World'

In [11]:
a = tf.constant(10)

In [12]:
b = tf.constant(20)

In [13]:
a + b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [15]:
a + b

<tf.Tensor 'add_4:0' shape=() dtype=int32>

In [16]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [17]:
result

30

In [18]:
const = tf.constant(10)

In [19]:
fill_mat = tf.fill((4,4), 10)

In [21]:
myzeros = tf.zeros((4,4))

In [22]:
myones = tf.ones((4,4))

In [23]:
myrandn = tf.random_normal((4,4), mean=0, stddev=1.0)

In [24]:
myrandu = tf.random_uniform((4,4), minval=0, maxval=1)

In [25]:
myzeros

<tf.Tensor 'zeros:0' shape=(4, 4) dtype=float32>

In [26]:
my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandu]

In [27]:
sess = tf.InteractiveSession()

In [29]:
for op in my_ops:
    print(sess.run(op))
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


[[ 0.92875439 -0.05327762  1.12236786 -0.53912282]
 [-2.82585549  0.11293926 -1.10843575  0.34788382]
 [-0.60906494  1.80086279  0.49855116 -1.02505612]
 [ 0.87354374  0.63101333 -0.66476351  0.63348401]]


[[ 0.12243998  0.63580811  0.48849988  0.90435481]
 [ 0.1079421   0.0655539   0.02549386  0.43678856]
 [ 0.7609129   0.2356056   0.92620873  0.95250475]
 [ 0.40682924  0.86120617  0.57278633  0.58336723]]




In [30]:
for op in my_ops:
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


[[-1.33101046 -1.20986485  1.39345777  0.45604318]
 [ 1.29692149 -0.62447208  0.72169203  2.13261843]
 [ 0.48952541 -1.43578124  0.37102231  0.37269792]
 [-0.26261806  0.9303636  -0.19193092  0.45935249]]


[[ 0.06921792  0.92113411  0.34671819  0.2604028 ]
 [ 0.0661577   0.97834575  0.82781613  0.13991094]
 [ 0.53971791  0.54302168  0.65365994  0.4457289 ]
 [ 0.7669313   0.22621322  0.71547484  0.01131332]]




In [31]:
a = tf.constant([ [1,2],
                 [3,4] ])

In [32]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [33]:
b = tf.constant([[10], [100]])

In [34]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [35]:
result = tf.matmul(a, b)

In [36]:
sess.run(result)

array([[210],
       [430]], dtype=int32)

In [37]:
result.eval()

array([[210],
       [430]], dtype=int32)